# Generated by Django 5.1.4 on 2025-01-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemcategory",
            name="slug",
            field=models.SlugField(blank=True, unique=True, null=True),
        ),
    ]
