# Generated by Django 5.1.4 on 2025-01-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_itemcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcategory",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
