# Generated by Django 5.1.3 on 2024-12-04 12:39

import django.core.validators
import django.utils.timezone
import exomarket_app.validators
import profanity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "exomarket_app",
            "0002_alter_cartitem_cart_alter_item_seller_itemcategory_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="itemcategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(
                default=django.utils.timezone.now,
                validators=[exomarket_app.validators.validate_user_age],
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(
                default="This is a <django.db.models.fields.related.ForeignKey>",
                validators=[profanity.validators.validate_is_profane],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter a valid phone number. The phone number must:\n- Be at least 6 characters long\n- May include an optional country code, starting with '+'\n- Contain only digits, spaces, parentheses, dashes ('-'), slashes ('/'), or dots ('.')\n- Allow optional separators (spaces, dashes, or slashes) between sections\n- Be a sequence of valid characters that form a plausible number.",
                        regex="(\\(?([\\d \\-\\)\\–\\+\\/\\(]+){6,}\\)?([ .\\-–\\/]?)([\\d]+))",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                fields=("username", "date_of_birth"), name="unique_username_birthday"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("item_name", "category", "seller"),
                name="unique_itemname_category_seller",
            ),
        ),
    ]
