# Generated by Django 5.1.3 on 2024-12-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exomarket_app",
            "0003_alter_customuser_options_alter_itemcategory_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, upload_to="item_images/"),
        ),
    ]
