# Generated by Django 5.1.3 on 2024-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exomarket_app", "0004_alter_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="rarity",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "Normal"),
                    ("M", "Magic"),
                    ("R", "Rare"),
                    ("S", "Set"),
                    ("U", "Unique"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RE", "Rogue Encampment"),
                    ("LG", "Lut Gholein"),
                    ("KD", "Kurast Docks"),
                    ("PF", "Pandemonium Fortress"),
                    ("HA", "Harrogath"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profession",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AM", "Amazon"),
                    ("NE", "Necromancer"),
                    ("BA", "Barbarian"),
                    ("MA", "Mage"),
                    ("PA", "Paladin"),
                    ("AS", "Assassin"),
                    ("DR", "Druid"),
                ],
                max_length=15,
            ),
        ),
    ]
