# Generated by Django 5.1.3 on 2024-12-11 17:54

import profanity.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exomarket_app", "0007_alter_item_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(
                default="This is an item of the category <django.db.models.fields.related.ForeignKey>",
                validators=[profanity.validators.validate_is_profane],
            ),
        ),
    ]
